---
kind: pipeline
type: docker
name: Use Sonarqube
steps:
  - image: aosapps/drone-sonar-plugin
    name: code-analysis
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
