kind: pipeline
type: docker
name: Use Sonarqube

steps:
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
    
  ver: 1.0
  timeout: 20
  sources: .
  level: DEBUG
  showProfiling: true
  commands:
    - dotnet sonarscanner begin o:"cjmanaguelod1895" k:"cjmanaguelod1895_SQL-Server-CICD" d:sonar.host.url="https://sonarcloud.io"
    - dotnet sonarscanner end
  

trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
